# Site
repository: selcukcihan/selcukcihan.github.io
favicon: images/favicon.ico

# Personal info
name: Selçuk Cihan
title: Software Development Engineer
emailname: selcukcihan
emaildomain: gmail.com
keywords: "selcuk, cihan, personal, software, developer, senior, resume, selçuk cihan, engineer, technologist, selcuk cihan, serverless, cloud, architect, amazon, aws"

# Social links

linkedin_username: selcukcihan
twitter_username: scihan
medium: bulut-aws
stackoverflow: "4281182"
github_username:  selcukcihan

google_analytics: "UA-68700480-1"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Building (and deprecating) software is my passion, with a focus on scalable backend services in the web ecosystem recently. You will find me most useful in crafting solutions, by putting customer first and ensuring operational excellence. I'm an ex-Amazonian, a **certified AWS solutions architect** and available for hire on <a target="_blank" href="https://www.toptal.com/resume/selcuk-cihan">Toptal</a>. I provide <a target="_blank" href="https://www.bulutla.com">AWS training</a> as well.

  Keywords: <mark>AWS</mark> <mark>Serverless</mark> <mark>Python</mark> <mark>Java</mark>

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
experience_title: Employment

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  <small><q>Hofstadter's Law: It always takes longer than you expect, even when you take into account Hofstadter's Law.</q></small>

  Comfortable taking on work in any tech stack, though Serverless, Java and Python have been a recurring theme in the past few years for me. For details, have a look at my <a href="/resume/selcukcihan.pdf">Curriculum Vitae</a> <small>(which may refer you to this page, in that case be conscious about the infinite loop you are in or you might never reach out to me!)</small>.

  #### Frameworks/Runtimes
  <mark>Django</mark> <mark>Spring</mark> <mark>Serverless</mark> <mark>Node.js</mark> <mark>Angular</mark>

  #### Languages
  <mark>Java</mark> <mark>Python 3</mark> <mark>Python 2</mark> <mark>JavaScript</mark> <mark>C</mark> <mark>C#</mark> <mark>Perl</mark> <mark>C++</mark> <mark>SQL</mark>

  #### AWS
  <mark>CloudWatch</mark> <mark>Kinesis</mark> <mark>SQS</mark> <mark>Lambda</mark> <mark>Step Functions</mark> <mark>Cognito</mark> <mark>IAM</mark> <mark>CloudFormation</mark> <mark>CloudFront</mark>

  #### Paradigms
  <mark>Unit Testing</mark> <mark>DevOps</mark> <mark>Agile</mark>

  #### Storage Solutions
  <mark>AWS DynamoDB</mark> <mark>AWS S3</mark> <mark>AWS RDS</mark> <mark>PostgreSQL</mark> <mark>Oracle SQL</mark> <mark>Microsoft SQL Server</mark>

  #### Miscellaneous
  <mark>Linux</mark> <mark>Docker</mark> <mark>Elasticsearch</mark>

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
